env:
  matrix:
    - EMACS=emacs23
    - EMACS=emacs24
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot

install:
  - if [[ "$EMACS"= 'emacs23' ]]; then
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs23-gtk emacs23-el curl;
    fi
  - if [[ "$EMACS" = 'emacs24' ]]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [[ "$EMACS" = 'emacs-snapshot' ]]; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs-snapshot emacs-snapshot-el;
    fi

before_script:
  - if [[ "$EMACS" = 'emacs23' ]]; then
      curl 'http://git.savannah.gnu.org/cgit/emacs.git/plain/lisp/emacs-lisp/ert.el?h=emacs-24.3' > ert.el
    fi

script: make test
